#!/bin/bash
# Nek5000 build config file
# (c) 2008,2009,2010 UCHICAGO ARGONNE, LLC

# source path 
SOURCE_ROOT="$HOME/git/aomp-test/openmpapps/Nekbone/src"

# Fortran compiler
F77="flang"

# C compiler
CC="clang"

# pre-processor symbol list 
# (set PPLIST=? to get a list of available symbols)
# NEKCOMM, NEKDLAY, BG
PPLIST=" "


# OPTIONAL SETTINGS
# -----------------

# enable MPI (default true)
IFMPI="false"

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules 
#USR="foo.o"

# linking flags
USR_LFLAGS="-fopenmp -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx900"

# generic compiler flags
#G="-g"

# optimization flags
OPT_FLAGS_STD="-O3"
OPT_FLAGS_STD="-O3"

###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
# assign version tag
mver=1
# overwrite source path with optional 2nd argument
if [ -d $2 ] && [ $# -eq 2 ]; then
  SOURCE_ROOT="$HOME/git/aomp-test/openmpapps/Nekbone/src"
  echo "change source code directory to: ", $SOURCE_ROOT
fi
# do some checks and create makefile
ls -l  $SOURCE_ROOT/makenek.inc
source $SOURCE_ROOT/makenek.inc
# compile
make -j4 -f makefile 2>&1 | tee compiler.out
exit 0
